/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "Test.h"
#include <time.h>
#include <stdio.h>
#define MAXBUFSIZE 1024
/** Initializes the Test module */

typedef struct PACKED
{
    char name[20];
    long total;
    char name2[20];
    long free;
}MEM_OCCUPY;
double get_memory_total();
void get_mem_occupy(MEM_OCCUPY * mem);
void
init_Test(void)
{
    const oid GetTime_oid[] = { 1,3,6,1,4,1,16535,1,1 };
    
    DEBUGMSGTL(("Test", "Initializing\n"));
    
    netsnmp_register_scalar(
                            netsnmp_create_handler_registration("GetTime", handle_GetTime,
                                                                GetTime_oid, OID_LENGTH(GetTime_oid),
                                                                HANDLER_CAN_RONLY
                                                                ));
}

int
handle_GetTime(netsnmp_mib_handler *handler,
               netsnmp_handler_registration *reginfo,
               netsnmp_agent_request_info   *reqinfo,
               netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
     "instance", as it's "magically" handled for us.  */
    
    /* a instance handler also only hands us one request at a time, so
     we don't need to loop over a list of requests; we'll only get one. */
    time_t t;
    switch(reqinfo->mode) {
            
        case MODE_GET:
            time(&t);
        {  char szTime[100];
            
            sprintf(szTime, "%f", get_memory_total());
            
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     /* XXX: a pointer to the scalar's data */
                                     szTime,
                                     /* XXX: the length of the data in bytes */strlen(szTime));
            break;
        }
            
        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_GetTime\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }
    
    return SNMP_ERR_NOERROR;
}
//内存总量
double get_memory_total(){
    MEM_OCCUPY mem;
    get_mem_occupy(&mem);
    double memory_total=mem.total;
    return memory_total;
}
void get_mem_occupy(MEM_OCCUPY * mem){
    FILE * fd;
    char buff[MAXBUFSIZE];
    fd = fopen("/proc/meminfo","r");
    fgets (buff, sizeof(buff), fd);
    sscanf (buff, "%s %ld", mem->name,&mem->total);
    fgets (buff, sizeof(buff), fd);
    sscanf (buff, "%s %ld", mem->name2,&mem->free);
    fclose(fd);
}
